# =============================================================================
# PlantVelocity: class.R
# Core S4 class definition and object-construction utilities for PlantVelocity.
#
# File structure:
#   Part 1 -- plantvelo S4 class definition
#              Unified container for expression layers, smoothed moments,
#              kinetic parameters, velocity results, graphs, and metadata
#   Part 2 -- create_plantvelo() public constructor
#              Build a plantvelo object from a Seurat object and a loom file
#   Part 3 -- Internal helper functions
#              Read loom layers, align barcode/gene order, and assemble
#              genes x cells matrices for @layers
#
# This module defines the fundamental data structure used throughout the
# PlantVelocity workflow.
# =============================================================================

#' plantvelo S4 Class
#'
#' Container for RNA velocity analysis of plant single-cell data.
#' Stores raw count layers, smoothed moments, kinetic parameters, velocity
#' vectors, and all derived graphs in a single object.
#'
#' @slot assays Named list of Seurat assay objects (typically \code{RNA}).
#' @slot meta.data data.frame of per-cell metadata (one row per cell).
#' @slot layers Named list of genes x cells matrices: \code{spliced},
#'   \code{unspliced}, \code{ir} (optional intron-retained), \code{velocity},
#'   \code{velocity_u}, \code{fit_t}, \code{fit_tau}, etc.
#' @slot reductions Named list of dimensionality reductions (Seurat
#'   \code{DimReduc} objects or plain matrices).  Includes PCA, UMAP/tSNE, and
#'   velocity embeddings (e.g. \code{velocity_umap}).
#' @slot active.ident Factor of cell identities (mirrors Seurat
#'   \code{Idents()}).
#' @slot graphs Named list of graph objects: \code{neighbors} (KNN graph with
#'   \code{connectivities} and \code{distances}), \code{velocity_graph},
#'   \code{velocity_graph_neg}.
#' @slot moments Named list of cells x genes smoothed expression matrices:
#'   \code{Ms} (spliced), \code{Mu} (unspliced), and optional \code{Mr} (IR).
#' @slot kinetics Named list; \code{params} is a genes x parameters data.frame
#'   of EM-fitted kinetic rates from \code{recover_dynamics()}.
#' @slot velocity Named list; \code{genes} is a named logical vector of
#'   high-quality velocity genes; \code{stream} stores the stream-field
#'   data.frame from \code{compute_velocity_stream()}.
#' @slot misc Named list for miscellaneous metadata: run parameters, IR gene
#'   statistics (\code{ir_gene_stats}), driver gene statistics
#'   (\code{velocity_gene_stats}), and merged-object bookkeeping.
#'
#' @exportClass plantvelo
setClass(
  "plantvelo",
  slots = list(
    assays       = "list",
    meta.data    = "data.frame",
    layers       = "list",
    reductions   = "list",
    active.ident = "factor",
    graphs       = "list",
    moments      = "list",
    kinetics     = "list",
    velocity     = "list",
    misc         = "list"
  ),
  prototype = list(
    assays       = list(),
    meta.data    = data.frame(),
    layers       = list(),
    reductions   = list(),
    active.ident = factor(),
    graphs       = list(),
    moments      = list(),
    kinetics     = list(),
    velocity     = list(),
    misc         = list()
  )
)

#' @title Create a plantvelo Object from a Seurat Object and a Loom File
#' @description
#' Read a loom file generated by \code{plantvelo run}, align its spliced,
#' unspliced, and (optionally) intron-retained count matrices to the cells and
#' genes in a Seurat object, and assemble a \code{plantvelo} object for
#' downstream RNA velocity analysis.
#'
#' All Seurat cell names must be present in the loom
#' \code{col_attrs/CellID}, and all Seurat feature names must be present in the
#' selected loom \code{row_attrs} field. Requires Seurat v5 / SeuratObject v5.
#'
#' @param seurat_object A Seurat object (v5+) with at least one dimensionality
#'   reduction (PCA required for \code{build_neighbor_graph()}).
#' @param assays Character scalar. Name of the assay to carry over from the
#'   Seurat object. Default \code{"RNA"}.
#' @param loom_path Character scalar. Path to the loom file produced by
#'   \code{plantvelo run} (must contain \code{layers/spliced} and
#'   \code{layers/unspliced}).
#' @param input_ident Character scalar or \code{NULL}. Column in
#'   \code{@meta.data} (or identity value) passed to \code{SetIdent()} to
#'   update the active cell identities.  \code{NULL} keeps the existing
#'   identities. Default \code{NULL}.
#' @param loom_gene_attr Character scalar. Name of the loom \code{row_attrs}
#'   field used to match Seurat feature names. Default \code{"Gene"}. Use
#'   \code{"Accession"} when Seurat row names contain gene accessions.
#'
#' @return A plantvelo object.
#' @examples
#' \dontrun{
#' pv <- create_plantvelo(
#'   seurat_object = seob,
#'   assays = "RNA",
#'   loom_path = "plantvelo_output.loom",
#'   input_ident = "cell_type"
#' )
#'
#' pv_accession <- create_plantvelo(
#'   seurat_object = seob,
#'   loom_path = "plantvelo_output.loom",
#'   loom_gene_attr = "Accession"
#' )
#' }
#' @export
create_plantvelo <- function(seurat_object,
                             assays = "RNA",
                             loom_path = NULL,
                             input_ident = NULL,
                             loom_gene_attr = "Gene"){

  # ----------------input validation----------------

  if (!is.character(loom_gene_attr) || length(loom_gene_attr) != 1L ||
      is.na(loom_gene_attr) || !nzchar(trimws(loom_gene_attr))) {
    stop("`loom_gene_attr` must be a single, non-empty, non-NA character value.")
  }
  if (grepl("/", loom_gene_attr, fixed = TRUE)) {
    stop(
      "`loom_gene_attr` must be an attribute name such as \"Gene\" or ",
      "\"Accession\", not a full path."
    )
  }

  if (!requireNamespace("Seurat", quietly = TRUE)) {
    stop("Package `Seurat` is required to create a plantvelo object.")
  }
  if (!requireNamespace("SeuratObject", quietly = TRUE)) {
    stop("Package `SeuratObject` is required to create a plantvelo object.")
  }
  if (!requireNamespace("hdf5r", quietly = TRUE)) {
    stop("Package `hdf5r` is required to read loom files.")
  }

  seurat_ver <- utils::packageVersion("Seurat")
  if (seurat_ver < package_version("5.0.0")) {
    stop(
      paste0(
        "plantvelo currently requires Seurat v5 / SeuratObject v5.\n",
        "Detected SeuratObject version: ", as.character(seurat_ver), "\n",
        "Please upgrade Seurat/SeuratObject to version 5."
      )
    )
  }

  if (!inherits(seurat_object, "Seurat")) {
    stop("`seurat_object` must be a Seurat object.")
  }

  if (is.null(loom_path) || !nzchar(loom_path) || !file.exists(loom_path)) {
    stop("Provide `loom_path` to load spliced, unspliced, and intron-retained matrices.")
  }

  if (assays %in% names(seurat_object@assays)) {
    counts <- list(RNA = seurat_object@assays[[assays]])
  } else {
    stop(paste0("Assay '", assays, "' not found in the Seurat object."))
  }

  reductions <- seurat_object@reductions
  if (length(reductions) == 0) {
    stop("No dimensionality reductions found in the Seurat object, please run `RunPCA` and `RunUMAP`/`RunTSNE` before creating the plantvelo object.")
  }

  if (!is.null(input_ident)) {
    seurat_object <- Seurat::SetIdent(seurat_object, value = input_ident)
  }

  loom_layers <- tryCatch(
    .read_loom_layers(loom_path, seurat_object, loom_gene_attr),
    error = function(e) {
      stop(
        "Failed to read loom file: ", loom_path, "\n",
        "Reason: ", conditionMessage(e), "\n",
        "Tips:\n",
        "  1. Confirm the file was generated by velocyto or plantvelo run.\n",
        "  2. Check that spliced/unspliced layers exist in the loom file.\n",
        "  3. Verify barcode formats match between Seurat object and loom file."
      )
    }
  )

  plantvelo <- methods::new("plantvelo",
                            assays = counts,
                            meta.data = seurat_object@meta.data,
                            layers = loom_layers,
                            reductions = reductions,
                            active.ident = SeuratObject::Idents(seurat_object))

  message("PlantVelocity object created.")
  if (!is.null(plantvelo@layers[["ir"]])) {
    message(
      "Successfully created plantvelo object with spliced, unspliced, and intron-retained layers."
    )
  } else {
    message(
      "Successfully created plantvelo object with spliced and unspliced layers."
    )
  }
  message("Version: PlantVelocity v0.4.0\n",
          "Author: Jdluttzxr\n")
  return(plantvelo)
}

# =============================================================================
# Internal helper functions
# =============================================================================

# Align a loom matrix (cells x genes) to the Seurat cell/gene order and
# transpose to genes x cells (consistent with @layers orientation).
.align_loom_seurat <- function(seurat_object, matrix) {
  seurat_genes <- rownames(seurat_object)
  seurat_cells <- colnames(seurat_object)
  align_mtx <- matrix[seurat_cells, seurat_genes, drop = FALSE]
  t_align_mtx <- t(align_mtx)
  return(t_align_mtx)
}

# Read all layers from a loom file and align them to the Seurat object.
# Stops with clear messages if required keys or Seurat cell/gene names are
# missing.
.read_loom_layers <- function(loom_path, seurat_object,
                              loom_gene_attr = "Gene") {
  if (!requireNamespace("hdf5r", quietly = TRUE)) {
    stop("Package `hdf5r` is required to read loom files.")
  }

  loom <- tryCatch(
    hdf5r::H5File$new(loom_path, mode = "r"),
    error = function(e) {
      stop(
        "Cannot open loom file '", loom_path, "'.\n",
        "Reason: ", conditionMessage(e), "\n",
        "Ensure the file is a valid HDF5/loom file and is not corrupted."
      )
    }
  )
  on.exit(try(loom$close_all(), silent = TRUE), add = TRUE)

  loom_gene_key <- paste0("row_attrs/", loom_gene_attr)
  if (!loom$exists(loom_gene_key)) {
    available_row_attrs <- tryCatch(
      as.character(loom[["row_attrs"]]$ls()$name),
      error = function(e) character(0)
    )
    available_row_attrs <- if (length(available_row_attrs) > 0) {
      paste(available_row_attrs, collapse = ", ")
    } else {
      "<none found>"
    }
    stop(
      "Requested loom gene attribute key '", loom_gene_key,
      "' was not found.\n",
      "Available row_attrs fields: ", available_row_attrs, "\n",
      "Set `loom_gene_attr` to an available field name, commonly ",
      "\"Gene\" or \"Accession\"."
    )
  }

  # check for required keys and provide detailed error if any are missing
  required_keys <- c("col_attrs/CellID", "layers/spliced",
                     "layers/unspliced")
  missing_keys <- required_keys[
    !vapply(required_keys, function(k) loom$exists(k), logical(1))
  ]
  if (length(missing_keys) > 0) {
    stop(
      "The following required keys are missing from the loom file:\n",
      paste0("  ", missing_keys, collapse = "\n"), "\n",
      "Ensure the loom file was generated by velocyto or plantvelo run."
    )
  }

  loom_genes <- loom[[loom_gene_key]][]
  loom_cells <- loom[["col_attrs/CellID"]][]

  seurat_cells <- colnames(seurat_object)
  seurat_genes <- rownames(seurat_object)
  missing_cells <- setdiff(seurat_cells, loom_cells)
  missing_genes <- setdiff(seurat_genes, loom_genes)

  if (length(missing_cells) > 0) {
    stop(
      "Some Seurat cells are missing from the loom file.\n",
      "  Seurat cells: ", length(seurat_cells), "\n",
      "  Loom cells: ", length(loom_cells), "\n",
      "  Missing Seurat cells: ", length(missing_cells), "\n",
      "  Examples (up to 5): ",
      paste(head(missing_cells, 5), collapse = ", "), "\n",
      "Verify that sample prefixes and barcode formats match between the inputs."
    )
  }

  if (length(missing_genes) > 0) {
    alternative_gene_attr <- if (identical(loom_gene_attr, "Accession")) {
      "Gene"
    } else {
      "Accession"
    }
    stop(
      "Some Seurat feature names are missing from loom key '",
      loom_gene_key, "'.\n",
      "  Seurat genes: ", length(seurat_genes), "\n",
      "  Loom genes: ", length(loom_genes), "\n",
      "  Missing Seurat genes: ", length(missing_genes), "\n",
      "  Examples (up to 5): ",
      paste(head(missing_genes, 5), collapse = ", "), "\n",
      "If the Seurat feature naming scheme differs, try `loom_gene_attr = ",
      "\"", alternative_gene_attr, "\"`."
    )
  }

  if (!all(grepl("^.+_[ACGTN]+-1$", loom_cells)) ||
      !all(grepl("^.+_[ACGTN]+-1$", seurat_cells))) {
    stop("Cell names must be in the format {sample_name}_barcode-1")
  }

  # spliced / unspliced layer
  spliced <- loom[["layers/spliced"]][, ]
  rownames(spliced) <- loom_cells
  colnames(spliced) <- loom_genes
  spliced <- .align_loom_seurat(seurat_object, spliced)

  unspliced <- loom[["layers/unspliced"]][, ]
  rownames(unspliced) <- loom_cells
  colnames(unspliced) <- loom_genes
  unspliced <- .align_loom_seurat(seurat_object, unspliced)

  # intron retained layer
  if (loom$exists("layers/retained")) {
    ir <- loom[["layers/retained"]][, ]
    rownames(ir) <- loom_cells
    colnames(ir) <- loom_genes
    ir <- .align_loom_seurat(seurat_object, ir)

    layers <- list(spliced = spliced, unspliced = unspliced, ir = ir)
  } else {
    layers <- list(spliced = spliced, unspliced = unspliced)
  }
  return(layers)
}
